spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mariadb://localhost:3306/test_db?createDatabaseIfNotExist=true
    username: root
    password: 123
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    open-in-view: false
server:
  error:
    include-message: always
    include-exception: true
springdoc:
  swagger-ui:
    path: /swagger-ui
